const KEY="corsa-e-suivi-v1";let charges=load(),monthlyChart,temperatureChart;const $=id=>document.getElementById(id);
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"[]").sort((a,b)=>new Date(a.date)-new Date(b.date))}catch{return[]}}function save(){localStorage.setItem(KEY,JSON.stringify(charges))}
function euro(v){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(v||0)}function num(v,d=1){return v==null||Number.isNaN(v)?"—":Number(v).toFixed(d).replace(".",",")}function dateLabel(d){return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(new Date(d))}function monthKey(d){let x=new Date(d);return x.getFullYear()+"-"+String(x.getMonth()+1).padStart(2,"0")}function monthLabel(k){let [y,m]=k.split("-");return new Intl.DateTimeFormat("fr-FR",{month:"short",year:"2-digit"}).format(new Date(+y,+m-1,1))}
function distanceFor(i){return i>0?Math.max(0,charges[i].odometer-charges[i-1].odometer):null}function consumptionFor(i){let km=distanceFor(i);return km>0?charges[i].kwh/km*100:null}
function render(){const current=monthKey(new Date()),mc=charges.filter(c=>monthKey(c.date)===current);$("monthCost").textContent=euro(mc.reduce((s,c)=>s+c.cost,0));$("monthCostDetail").textContent=euro(mc.filter(c=>c.location==="home").reduce((s,c)=>s+c.cost,0))+" domicile · "+euro(mc.filter(c=>c.location==="external").reduce((s,c)=>s+c.cost,0))+" extérieur";let kms=mc.reduce((s,c)=>{let i=charges.indexOf(c);return s+(i>0?distanceFor(i):0)},0);$("monthKm").textContent=num(kms,0)+" km";let energy=mc.reduce((s,c)=>s+c.kwh,0);$("monthConsumption").textContent=kms>0?num(energy/kms*100,1)+" kWh/100 km":"—";let temps=mc.map(c=>c.temperature).filter(v=>v!==null&&v!=="").map(Number);$("monthTemp").textContent="Température moyenne : "+(temps.length?num(temps.reduce((a,b)=>a+b,0)/temps.length,1)+" °C":"—");$("monthCharges").textContent=mc.length;$("allCharges").textContent=charges.length+" au total";
const tbody=$("history");tbody.innerHTML="";[...charges].reverse().forEach((c,ri)=>{let i=charges.length-1-ri,tr=document.createElement("tr"),km=distanceFor(i),con=consumptionFor(i);tr.innerHTML="<td>"+dateLabel(c.date)+"</td><td>"+num(c.odometer,0)+" km</td><td>"+num(c.kwh,2)+"</td><td>"+euro(c.cost)+"</td><td>"+(c.location==="home"?"Domicile":"Extérieur")+"</td><td>"+num(c.temperature,1)+"</td><td>"+(km==null?"—":num(km,0)+" km")+"</td><td>"+(con==null?"—":num(con,1)+" kWh/100")+"</td><td><button class='delete' data-i='"+i+"'>Suppr.</button></td>";tbody.appendChild(tr)});tbody.querySelectorAll(".delete").forEach(b=>b.onclick=()=>{charges.splice(+b.dataset.i,1);save();render()});drawCharts()}
function monthlyData(){const groups={};charges.forEach((c,i)=>{const k=monthKey(c.date);if(!groups[k])groups[k]={home:0,external:0,kwh:0,km:0};groups[k][c.location==="home"?"home":"external"]+=c.cost;groups[k].kwh+=c.kwh;const km=distanceFor(i);if(km>0)groups[k].km+=km});let keys=Object.keys(groups).sort(),p=$("period").value;if(p!=="all")keys=keys.slice(-Number(p));return{keys,g:groups}}
function drawCharts(){if(!window.Chart)return;const {keys,g}=monthlyData();if(monthlyChart)monthlyChart.destroy();monthlyChart=new Chart($("monthlyChart"),{type:"line",data:{labels:keys.map(monthLabel),datasets:[{label:"€ domicile",data:keys.map(k=>g[k].home),tension:.25},{label:"€ extérieur",data:keys.map(k=>g[k].external),tension:.25},{label:"km parcourus",data:keys.map(k=>g[k].km),tension:.25},{label:"kWh/100 km",data:keys.map(k=>g[k].km?g[k].kwh/g[k].km*100:null),tension:.25}]},options:{responsive:true,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"bottom"}},scales:{y:{beginAtZero:true}}}});if(temperatureChart)temperatureChart.destroy();const points=charges.map((c,i)=>({x:c.temperature===""?null:Number(c.temperature),y:consumptionFor(i)})).filter(p=>p.x!=null&&p.y!=null);temperatureChart=new Chart($("temperatureChart"),{type:"scatter",data:{datasets:[{label:"Consommation selon température",data:points}]},options:{responsive:true,plugins:{legend:{position:"bottom"}},scales:{x:{title:{display:true,text:"Température (°C)"}},y:{title:{display:true,text:"kWh/100 km"},beginAtZero:true}}}})}
$("chargeForm").addEventListener("submit",e=>{e.preventDefault();const c={date:$("date").value,odometer:Number($("odometer").value),kwh:Number($("kwh").value),cost:Number($("cost").value),location:$("location").value,temperature:$("temperature").value===""?"":Number($("temperature").value),note:$("note").value.trim()};if(charges.length&&c.odometer<charges[charges.length-1].odometer){alert("Le compteur doit être supérieur ou égal au dernier relevé.");return}charges.push(c);charges.sort((a,b)=>new Date(a.date)-new Date(b.date));save();e.target.reset();$("date").value=new Date().toISOString().slice(0,16);render()});
$("period").onchange=drawCharts;$("clearBtn").onclick=()=>{if(confirm("Effacer toutes les données de ce navigateur ?")){charges=[];save();render()}};$("exportBtn").onclick=()=>{const head=["date","odometer","kwh","cost","location","temperature","note"],rows=charges.map(c=>head.map(k=>JSON.stringify(c[k]??"")).join(";")),blob=new Blob(["\ufeff"+head.join(";")+"\n"+rows.join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="corsa-e-suivi.csv";a.click();URL.revokeObjectURL(a.href)};
$("importInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text(),lines=text.replace(/^\ufeff/,"").trim().split(/\r?\n/);if(lines.length<2)return;const rows=lines.slice(1).map(parseCsvLine),imported=rows.map(r=>({date:r[0],odometer:Number(r[1]),kwh:Number(r[2]),cost:Number(r[3]),location:r[4]||"home",temperature:r[5]===""?"":Number(r[5]),note:r[6]||""})).filter(c=>c.date&&!Number.isNaN(c.odometer));charges=[...charges,...imported].sort((a,b)=>new Date(a.date)-new Date(b.date));save();render();e.target.value=""};
function parseCsvLine(line){let out=[],cur="",q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch==='"'&&line[i+1]==='"'){cur+='"';i++}else if(ch==='"')q=!q;else if(ch===";"&&!q){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out}
$("date").value=new Date().toISOString().slice(0,16);render();